/*

 POND1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Harry\Desktop\GBA stuff\TileDesigner\TileDesigns\Floors.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define PondMapWidth 20
#define PondMapHeight 18
#define PondMapBank 0

extern unsigned char PondMap[];

/* End of POND1.H */
